spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id= true

spring.endpoint.gateway.access= READ_ONLY

PRODUCT_SERVICE_ID: lb://PRODUCT-SERVICE