eureka:
  instance:
  preferIpAddress: true
  
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info

#This is name of Services
PRODUCT_SERVICE_ID: lb://PRODUCT-SERVICE
INVENTORY_SERVICE_ID: lb://INVENTORY-SERVICE
CART_ORDER_SERVICE_ID: lb://CART-ORDER-SERVICE
