# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# HIKARICP CONFIGURATION
# =========================================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# ===============================

# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Time Zone
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#ImageKit
imagekit.id=nexBuy
imagekit.public-key=public_Rtg7Q3mR4yx87Y2h7RPVYtO5gFs=
imagekit.private-key=private_e1Izos/QrVlw4MIFtJmc5VDhtT4=
imagekit.url-endpoint=https://ik.imagekit.io/nexBuy
imagekit.folder=/products